
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CATEGORIA_E CATEGORIA_S DESCRIPCION_E DESCRIPCION_S ID_E ID_S INGREDIENTES_E INGREDIENTES_S INGREDIENTE_E INGREDIENTE_S MARCA_E MARCA_S NOMBRE_E NOMBRE_S PRECIO_E PRECIO_S PRODUCTOS_E PRODUCTOS_S PRODUCTO_E PRODUCTO_S STOCK_E STOCK_S TEXTproductos : PRODUCTOS_S lista_productos PRODUCTOS_Elista_productos : productolista_productos : producto lista_productosproducto : PRODUCTO_S ID_S TEXT ID_E NOMBRE_S TEXT NOMBRE_E MARCA_S TEXT MARCA_E CATEGORIA_S TEXT CATEGORIA_E PRECIO_S TEXT PRECIO_E STOCK_S TEXT STOCK_E DESCRIPCION_S TEXT DESCRIPCION_E INGREDIENTES_S lista_ingredientes INGREDIENTES_E PRODUCTO_Elista_ingredientes : INGREDIENTE_S TEXT INGREDIENTE_Elista_ingredientes : INGREDIENTE_S TEXT INGREDIENTE_E lista_ingredientes'
    
_lr_action_items = {'PRODUCTOS_S':([0,],[2,]),'$end':([1,6,],[0,-1,]),'PRODUCTO_S':([2,4,34,],[5,5,-4,]),'PRODUCTOS_E':([3,4,7,34,],[6,-2,-3,-4,]),'ID_S':([5,],[8,]),'TEXT':([8,11,14,17,20,23,26,31,],[9,12,15,18,21,24,27,33,]),'ID_E':([9,],[10,]),'NOMBRE_S':([10,],[11,]),'NOMBRE_E':([12,],[13,]),'MARCA_S':([13,],[14,]),'MARCA_E':([15,],[16,]),'CATEGORIA_S':([16,],[17,]),'CATEGORIA_E':([18,],[19,]),'PRECIO_S':([19,],[20,]),'PRECIO_E':([21,],[22,]),'STOCK_S':([22,],[23,]),'STOCK_E':([24,],[25,]),'DESCRIPCION_S':([25,],[26,]),'DESCRIPCION_E':([27,],[28,]),'INGREDIENTES_S':([28,],[29,]),'INGREDIENTE_S':([29,35,],[31,31,]),'INGREDIENTES_E':([30,35,36,],[32,-5,-6,]),'PRODUCTO_E':([32,],[34,]),'INGREDIENTE_E':([33,],[35,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'productos':([0,],[1,]),'lista_productos':([2,4,],[3,7,]),'producto':([2,4,],[4,4,]),'lista_ingredientes':([29,35,],[30,36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> productos","S'",1,None,None,None),
  ('productos -> PRODUCTOS_S lista_productos PRODUCTOS_E','productos',3,'p_productos','archivo_yacc.py',8),
  ('lista_productos -> producto','lista_productos',1,'p_lista_productos_uno','archivo_yacc.py',16),
  ('lista_productos -> producto lista_productos','lista_productos',2,'p_lista_productos_mas','archivo_yacc.py',20),
  ('producto -> PRODUCTO_S ID_S TEXT ID_E NOMBRE_S TEXT NOMBRE_E MARCA_S TEXT MARCA_E CATEGORIA_S TEXT CATEGORIA_E PRECIO_S TEXT PRECIO_E STOCK_S TEXT STOCK_E DESCRIPCION_S TEXT DESCRIPCION_E INGREDIENTES_S lista_ingredientes INGREDIENTES_E PRODUCTO_E','producto',26,'p_producto','archivo_yacc.py',24),
  ('lista_ingredientes -> INGREDIENTE_S TEXT INGREDIENTE_E','lista_ingredientes',3,'p_lista_ingredientes_uno','archivo_yacc.py',45),
  ('lista_ingredientes -> INGREDIENTE_S TEXT INGREDIENTE_E lista_ingredientes','lista_ingredientes',4,'p_lista_ingredientes_mas','archivo_yacc.py',50),
]
